services:
  postgres:
    image: postgres:15
    container_name: shareit-postgres
    environment:
      POSTGRES_DB: shareit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "6543:5432"